version: '3.0'
services:
  webserv:
    container_name: webserv
    image: webserv:${USER}
    build:
      context: ./requirements/webserv
      dockerfile: Dockerfile
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - webserv-data:/webserv
    ports:
      - 80:80
      - "8000-9000:8000-9000"
    networks:
      - docker-network
    restart: unless-stopped
networks:
  docker-network:
volumes:
  webserv-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/${USER}/webserv