version: '3.0'
services:
  nginx:
    container_name: nginx
    image: nginx:${USER}
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 22:22
      - "8000-9000:8000-9000"
    networks:
      - docker-network
    restart: unless-stopped
networks:
  docker-network:
